spring:
  application:
    name: camerashopapi

  datasource:
    url: jdbc:mariadb://192.168.1.177:3306/camerashopdb
    username: springapp
    password: "StrongPassword!1234"
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true